FROM python:3.6.0

WORKDIR /app
COPY flask-realworld-example-app/requirements /requirements
RUN pip install --upgrade pip && pip install --no-cache-dir -r /requirements/prod.txt
ENV FLASK_APP=/path/to/autoapp.py
ENV FLASK_DEBUG=0
COPY flask-realworld-example-app /app

CMD ['flask','run','--with-threads']